version: "3.7"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ['sh', './start.sh']
    volumes:
      - .:/app
    env_file:
      - settings.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
