version: "3.7"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ['sh', './start.sh']
    volumes:
      - .:/app
    env_file:
      - settings.env
    depends_on:
      - postgres  # Assuming you have a service named 'postgres'

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: harsh
      POSTGRES_PASSWORD: harsh@123
